# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3be5553bb54e9ab0889e0b9a1aa4c248e0f7574653cf51d7a7a6c59d2fffc4db888480886ae746955df7d9f57e9e4e7048ec23c433449b72647b0080ab6c55

test:
  secret_key_base: 7c72fad9380e20a74be4fe17a582522edaefd5ccd8da0e7a9f7cba3a80de7d199259926b7fcabd24af44f82125c735d60aa90852bd13bc240f90eb9615270b41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
