# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ece14fb4bf4c682fc3af99c48b285f0a2f4b2b66c5eac1f3c59f55c9e77fcd0bd1bc13fd530a5e98f98f3c41143450c23fe61faaecee8a3da1431f409eab23

test:
  secret_key_base: 7c101b48553f2f40c6ca34bdd6578af5aa50e2217d8b66f984e468d73ade243b4520c47354a816bd63c3cf1a8a6fc0a6e59bc8800e61da8b3c433ae59222bd72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
